version: '3'
name: 'play-scala-kafka'  # containers are prefixed with name

networks:
  app-tier:
    driver: bridge

services:

  kafka:
    image: 'bitnami/kafka:3.2.3'
    networks:
      - app-tier
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER

  # Main application
  app:
    build: .  # build from local Dockerfile
    restart: always
    depends_on:
      - kafka
    ports:
      - 9000:9000
    networks:
      - app-tier