services:
  db:
    image: postgres
    container_name: play-shop-compose
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=playshop

  # Database admin tool container (localhost:8080)
  db-adminer:
    image: adminer  # version defaults to 'latest'
    restart: always
    depends_on: # container startup will wait till 'db' container is in a running_state.
      # Note: it doesn't mean application within container has completed initialisation.
      # For more exhaustive state check see:
      #  https://docs.docker.com/compose/compose-file/compose-file-v3/#healthcheck
      #  https://stackoverflow.com/questions/47710767/what-is-the-alternative-to-condition-form-of-depends-on-in-docker-compose-versio
      - db
    ports:
      - 8080:8080

  play-scala-shoppping-cart:
    depends_on:
      - db
    build: .
    ports:
      - 9000:9000
    environment:
      - POSTGRES_DB_HOST=db
      - POSTGRES_DB_NAME=playshop
      - POSTGRES_DB_USERNAME=admin
      - POSTGRES_DB_PASSWORD=password
    restart: always
